### ISSUE TITLE
[Bug] Application debugging hangs with white screen on Node.js 15 on iOS and Android

### ISSUE THREAD

**Issue by supagu** [microsoft/vscode-react-native#1465]
# 🐛 What is the bug? How can we reproduce it?

I created a new react-native app:

react-native init test
then I opened it and added a launch configuration with "Debug iOS"

Try to run "Debug iOS" and it builds ok, and get deployed to my simulator. It loads the app, but then kicks me out of the app and seems to re-run it.
This time the app is stuck at "Downloading JavaScript bundle 100% (3563/3563)..."

NOTE I added: "trace": "verbose" to the Debug iOS configuration to try to get more info

## Expected behavior

What were you expecting to happen?
The app would load and let me debug it.

## Debug output

<details>
<summary>Debug Console</summary>

```text

From client: initialize({"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"reactnative","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-gb","supportsProgressReporting":true,"supportsInvalidatedEvent":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"supportsConfigurationDoneRequest":true,"supportsEvaluateForHovers":true,"supportTerminateDebuggee":true,"supportsCancelRequest":true}}
From client: launch({"name":"Debug iOS","cwd":"/Users/fabian/Projects/jpmedia/test","type":"reactnative","request":"launch","platform":"ios","trace":"verbose","__configurationTarget":5,"__sessionId":"380dd650-09df-456f-b75e-d2d435c2f959"})
/Users/fabian/Projects/jpmedia/test/.vscode/settings.json file doesn't exist or its content is incorrect. This file will be ignored.
Launching the application
Launching the application: {
  "name": "Debug iOS",
  "cwd": "/Users/fabian/Projects/jpmedia/test",
  "type": "reactnative",
  "request": "launch",
  "platform": "ios",
  "trace": "verbose",
  "__configurationTarget": 5,
  "__sessionId": "380dd650-09df-456f-b75e-d2d435c2f959",
  "sourceMaps": true,
  "enableDebug": true
}
Attaching to the application
Attaching to the application: {
  "name": "Debug iOS",
  "cwd": "/Users/fabian/Projects/jpmedia/test",
  "type": "reactnative",
  "request": "launch",
  "platform": "ios",
  "trace": "verbose",
  "__configurationTarget": 5,
  "__sessionId": "380dd650-09df-456f-b75e-d2d435c2f959",
  "sourceMaps": true,
  "enableDebug": true,
  "port": 8081
}
Starting debugger app worker.
About to download: http://localhost:8081/debugger-ui/debuggerWorker.js to: /Users/fabian/Projects/jpmedia/test/.vscode/.react/debuggerWorker.js
Established a connection with the Proxy (Packager) to the React Native application
From RN APP: {"id":10001,"method":"prepareJSRuntime"}
A new app worker lifetime was created.
Spawned debuggee process with pid 21461 listening to 5601
Debugger worker loaded runtime on port 5601
To RN APP: {"replyID":10001}
From RN APP: {"id":10002,"method":"executeApplicationScript","url":"http:\/\/localhost:8081\/index.bundle?platform=ios&dev=true&minify=false","inject":{"__fbBatchedBridgeConfig":"{\"remoteModuleConfig\":[null,null,[\"DatePickerManager\",null,[\"setNativeDate\"]],null,null,null,[\"PickerManager\",null,[\"setNativeSelectedIndex\"]],null,[\"RefreshControlManager\",null,[\"setNativeRefreshing\"]],null,null,[\"ScrollViewManager\",null,[\"getContentSize\",\"calculateChildFrames\",\"scrollTo\",\"scrollToEnd\",\"zoomToRect\",\"flashScrollIndicators\"]],null,null,[\"SwitchManager\",null,[\"setValue\"]],[\"UIManager\",{\"RCTPicker\":{\"directEventTypes\":{},\"bubblingEventTypes\":{\"topChange\":{\"phasedRegistrationNames\":{\"bubbled\":\"onChange\",\"captured\":\"onChangeCapture\"}}},\"NativeProps\":{\"fontSize\":\"NSNumber\",\"onChange\":\"BOOL\",\"accessibilityLabel\":\"NSString\",\"color\":\"UIColor\",\"items\":\"NSArray<NSDictionary *>\",\"textAlign\":\"NSTextAlignment\",\"fontWeight\":\"NSString\",\"fontStyle\":\"NSString\",\"selectedIndex\":\"NSInteger\",\"fontFamily\":\"NSString\"},\"Manager\":\"PickerManager\",\"baseModuleName\":\"RCTView\"},\"RCTScrollContentView\":{\"directEventTypes\":{},\"bubblingEventTypes\":{},\"NativeProps\":{},\"Manager\":\"ScrollContentViewManager\",\"baseModuleName\":\"RCTView\"},\"RCTScrollView\":{\"directEventTypes\":{\"topScrollBeginDrag\":{\"registrationName\":\"onScrollBeginDrag\"},\"topScrollEndDrag\":{\"registrationName\":\"onScrollEndDrag\"},\[...]
Packager requested runtime to load script from http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false
Script http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false downloaded to /Users/fabian/Projects/jpmedia/test/.vscode/.react/index.bundle
Running application test ({
    initialProps =     {
    };
    rootTag = 11;
})
 node_modules/react-native/Libraries/Utilities/RCTLog.js
Running "test" with {"rootTag":11,"initialProps":{}}
 node_modules/react-native/Libraries/Utilities/infoLog.js
To RN APP: {"replyID":10002,"result":null}
From RN APP: {"id":10003,"method":"flushedQueue","arguments":[]}
To RN APP: {"replyID":10003,"result":"[[20,20,39,39,39,39,39,41],[1,0,5,5,5,5,0,1],[[\"appStateDidChange\"],[2,3],[\"websocketMessage\"],[\"websocketOpen\"],[\"websocketClosed\"],[\"websocketFailed\"],[\"ws://localhost:8097\",null,{\"headers\":{}},0],[]],0]"}
From RN APP: {"id":10004,"method":"callFunctionReturnFlushedQueue","arguments":["HMRClient","setup",["ios","index.bundle","localhost",8081,true]]}
From RN APP: {"id":10005,"method":"callFunctionReturnFlushedQueue","arguments":["RCTLog","logIfNoNativeHook",["info","Running application test ({\n    initialProps =     {\n    };\n    rootTag = 11;\n})"]]}
From RN APP: {"id":10006,"method":"callFunctionReturnFlushedQueue","arguments":["AppRegistry","runApplication",["test",{"rootTag":11,"initialProps":{}}]]}
To RN APP: {"replyID":10004,"result":"[[39,39,39,39,39],[5,5,5,5,0],[[\"websocketMessage\"],[\"websocketOpen\"],[\"websocketClosed\"],[\"websocketFailed\"],[\"ws://localhost:8081/hot\",null,{\"headers\":{}},1]],8]"}
From RN APP: {"id":10007,"method":"invokeCallbackAndReturnFlushedQueue","arguments":[2,[{"app_state":"active"}]]}
To RN APP: {"replyID":10005,"result":"null"}
To RN APP: {"replyID":10006,"result":"[[29,29,29,29,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,35,35,35],[0,0,0,0,5,5,5,3,5,3,5,5,3,5,5,5,3,5,5,3,5,3,5,5,3,5,5,5,3,5,5,3,5,3,5,3,5,5,3,5,5,5,3,5,5,5,5,3,5,5,3,5,3,5,3,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,5,5,3,5,5,3,5,3,5,3,5,3,5,3,5,3,5,3,5,3,5,3,3,1,2,3],[[\"keyboardWillShow\"],[\"keyboardWillHide\"],[\"keyboardDidShow\"],[\"keyboardDidHide\"],[3,\"RCTImageView\",11,{\"accessibilityRole\":\"image\",\"source\":[{\"__packager_asset\":true,\"width\":512,\"height\":512,\"uri\":\"http://localhost:8081/assets/node_modules/react-native/Libraries/NewAppScreen/components/logo.png?platform=ios&hash=47ce6e77f039020ee2e76a10c1e988e9\",\"scale\":1}],\"overflow\":\"visible\",\"position\":\"absolute\",\"left\":0,\"right\":0,\"top\":0,\"bottom\":0,\"opacity\":0.2,\"resizeMode\":\"cover\",\"marginLeft\":-128,\"marginBottom\":-192}],[5,\"RCTRawText\",11,{\"text\":\"Welcome to React\"}],[7,\"RCTText\",11,{\"fontSize\":40,\"fontWeight\":\"600\",\"textAl[...]
To RN APP: {"replyID":10007,"result":"null"}
From RN APP: {"id":10008,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketFailed",{"message":"The operation couldn’t be completed. Connection refused","id":0}]]}
From RN APP: {"id":10009,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketOpen",{"id":1,"protocol":""}]]}
To RN APP: {"replyID":10008,"result":"[[36,39,39,39,39],[0,6,6,6,6],[[2,2000,1606878552214,false],[1],[1],[1],[1]],166]"}
To RN APP: {"replyID":10009,"result":"[[39,39,39],[1,1,1],[[\"{\\\"type\\\":\\\"log-opt-in\\\"}\",1],[\"{\\\"type\\\":\\\"register-entrypoints\\\",\\\"entryPoints\\\":[\\\"ws://localhost:8081/hot?bundleEntry=index.bundle&platform=ios\\\"]}\",1],[\"{\\\"type\\\":\\\"log\\\",\\\"level\\\":\\\"log\\\",\\\"data\\\":[\\\"JavaScript logs will appear in your environment console\\\"]}\",1]],171]"}
From RN APP: {"id":10010,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketMessage",{"type":"text","data":"{\"type\":\"update-start\",\"body\":{\"isInitialUpdate\":true}}","id":1}]]}
From RN APP: {"id":10011,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketMessage",{"type":"text","data":"{\"type\":\"update\",\"body\":{\"revisionId\":\"33dae96d294b3fd1\",\"isInitialUpdate\":true,\"added\":[],\"modified\":[],\"deleted\":[]}}","id":1}]]}
To RN APP: {"replyID":10010,"result":"null"}
To RN APP: {"replyID":10011,"result":"null"}
From RN APP: {"id":10012,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketMessage",{"type":"text","data":"{\"type\":\"update-done\"}","id":1}]]}
From RN APP: {"id":10013,"method":"callFunctionReturnFlushedQueue","arguments":["RCTDeviceEventEmitter","emit",["websocketMessage",{"type":"text","data":"{\"type\":\"bundle-registered\"}","id":1}]]}
To RN APP: {"replyID":10012,"result":"[[24],[1],[[]],174]"}
To RN APP: {"replyID":10013,"result":"null"}
From RN APP: {"id":10014,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveEvent",[227,"topLayout",{"target":227,"layout":{"y":0,"width":414,"height":896,"x":0}}]]}
To RN APP: {"replyID":10014,"result":"null"}
From RN APP: {"id":10015,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveEvent",[227,"topLayout",{"target":227,"layout":{"y":44,"width":414,"height":852,"x":0}}]]}
To RN APP: {"replyID":10015,"result":"null"}
From RN APP: {"id":10016,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveEvent",[227,"topLayout",{"target":227,"layout":{"y":0,"width":414,"height":896,"x":0}}]]}
To RN APP: {"replyID":10016,"result":"null"}
From RN APP: {"id":10017,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveEvent",[227,"topLayout",{"target":227,"layout":{"y":44,"width":414,"height":852,"x":0}}]]}
To RN APP: {"replyID":10017,"result":"null"}
From RN APP: {"id":10018,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveEvent",[227,"topLayout",{"target":227,"layout":{"y":44,"width":414,"height":818,"x":0}}]]}
To RN APP: {"replyID":10018,"result":"null"}
From RN APP: {"id":10019,"method":"callFunctionReturnFlushedQueue","arguments":["JSTimers","callTimers",[[2]]]}
To RN APP: {"replyID":10019,"result":"null"}
From RN APP: {"id":10020,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveTouches",["topTouchStart",[{"target":57,"pageY":486,"locationX":297,"locationY":2,"identifier":1,"pageX":321,"timestamp":16867784.753935002}],[0]]]}
To RN APP: {"replyID":10020,"result":"null"}
From RN APP: {"id":10021,"method":"callFunctionReturnFlushedQueue","arguments":["RCTEventEmitter","receiveTouches",["topTouchEnd",[{"target":57,"pageY":486,"locationX":297,"locationY":2,"identifier":1,"pageX":321,"timestamp":16867863.62142}],[0]]]}
To RN APP: {"replyID":10021,"result":"null"}
From RN APP: {"id":10022,"method":"callFunctionReturnFlushedQueue","arguments":["RCTLog","logIfNoNativeHook",["info","Invalidating <RCTCxxBridge: 0x7fef14c18610> (parent: <RCTBridge: 0x6000032b8bd0>, executor: RCTWebSocketExecutor)"]]}
To RN APP: {"replyID":10022,"result":"null"}
Invalidating <RCTCxxBridge: 0x7fef14c18610> (parent: <RCTBridge: 0x6000032b8bd0>, executor: RCTWebSocketExecutor)
 node_modules/react-native/Libraries/Utilities/RCTLog.js
From RN APP: {"method":"$disconnected"}
About to kill debuggee with pid 21461
From RN APP: {"id":10023,"method":"prepareJSRuntime"}
A new app worker lifetime was created.
Spawned debuggee process with pid 21500 listening to 31957
Debugger worker loaded runtime on port 31957
To RN APP: {"replyID":10023}
From RN APP: {"id":10024,"method":"executeApplicationScript","url":"http:\/\/localhost:8081\/index.bundle?platform=ios&dev=true&minify=false","inject":{"__fbBatchedBridgeConfig":"{\"remoteModuleConfig\":[null,null,[\"DatePickerManager\",null,[\"setNativeDate\"]],null,null,null,[\"PickerManager\",null,[\"setNativeSelectedIndex\"]],null,[\"RefreshControlManager\",null,[\"setNativeRefreshing\"]],null,null,[\"ScrollViewManager\",null,[\"getContentSize\",\"calculateChildFrames\",\"scrollTo\",\"scrollToEnd\",\"zoomToRect\",\"flashScrollIndicators\"]],null,null,[\"SwitchManager\",null,[\"setValue\"]],[\"UIManager\",{\"RCTPicker\":{\"directEventTypes\":{},\"bubblingEventTypes\":{\"topChange\":{\"phasedRegistrationNames\":{\"bubbled\":\"onChange\",\"captured\":\"onChangeCapture\"}}},\"NativeProps\":{\"fontSize\":\"NSNumber\",\"onChange\":\"BOOL\",\"accessibilityLabel\":\"NSString\",\"color\":\"UIColor\",\"items\":\"NSArray<NSDictionary *>\",\"textAlign\":\"NSTextAlignment\",\"fontWeight\":\"NSString\",\"fontStyle\":\"NSString\",\"selectedIndex\":\"NSInteger\",\"fontFamily\":\"NSString\"},\"Manager\":\"PickerManager\",\"baseModuleName\":\"RCTView\"},\"RCTScrollContentView\":{\"directEventTypes\":{},\"bubblingEventTypes\":{},\"NativeProps\":{},\"Manager\":\"ScrollContentViewManager\",\"baseModuleName\":\"RCTView\"},\"RCTScrollView\":{\"directEventTypes\":{\"topScrollBeginDrag\":{\"registrationName\":\"onScrollBeginDrag\"},\"topScrollEndDrag\":{\"registrationName\":\"onScrollEndDrag\"},\[...]


```
</details>

<details>
<summary>React Native output channel</summary>

```text

[Debug] Begin to activate...

[Debug] Extension version: 1.1.1

[Debug] Projects found: 1

[Debug] Add project: /Users/fabian/Projects/jpmedia/test

[Debug] React Native version: 0.63.4

[Debug] 'react-native' package with value '0.63.4' is found in 'dependencies' section of package.json

[Info] Starting Packager

[Debug] Executing command: /Users/fabian/Projects/jpmedia/test/node_modules/.bin/react-native start --port 8081

                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          
                 Welcome to React Native!
                Learn once, write anywhere


[Info] Packager started.

[Info] Prewarming bundle cache. This may take a while ...

[Info] About to get: http://localhost:8081/index.bundle?platform=ios

[Wed Dec 02 2020 13:35:38.184]  BUNDLE  ./index.js 

[Warning] The Bundle Cache was prewarmed.

[Info] Building and running application.

[Wed Dec 02 2020 13:38:40.274]  BUNDLE  ./index.js 

[Wed Dec 02 2020 13:38:40.802]  LOG      Running "test" with {"rootTag":1,"initialProps":{}}
[Info] Enable JS Debugging

[Info] About to search for plist in base folder: /Users/fabian/Library/Developer/CoreSimulator/Devices/BE3E25FE-CFB7-4572-8D5C-B7EC0DC77AA3/data/Containers/Data/Application pathAfter: Library/Preferences/org.reactjs.native.example.test.plist in each of the apps: 05BB4537-3C35-4320-9648-42368F1C7ACA,1270E27A-0A82-4E7F-923B-D86CF2346024,1799674F-1EF1-4510-9F01-A18C00F0EB14,17F733D6-21C3-47F1-9B95-18C2C6E04F57,1B565069-D392-43AF-972E-C21763AA8F4F,1DD10550-CF1E-4328-9323-45B009180C7C,24978EBD-2CE0-4C03-B6E6-02469C710DC3,2743A147-0DF1-4910-81E3-9B5EF03FDFF5,2FB01430-D44F-4A04-A931-FAB1D3F022AC,36E37E0E-2F2D-4C1C-A600-F310637BAAC2,3C50EA36-B050-428E-8CD8-653608546C06,3FB00141-9243-4DCD-938E-09AE16514072,4316F007-17A2-4238-BD1D-2543B0E59E1F,44D8E181-5F3B-496F-BF98-D5AE7CFE6C88,46531F6D-6FD3-4EEC-8E12-C10836F107EC,4D9C3F82-12DC-448C-B8AE-DED3F2951326,4E7A051B-18AF-435E-B38B-9F2C984B577D,53B6D5CD-4907-4DCD-9EB6-482A77CB4537,5400E774-3B4B-488C-81D5-1A7C80244A8A,542B22EB-2612-410D-8A0A-F543D06FB9E2,54DB49A0-E051-4753-9A2B-137F7CB84AE0,645290CC-B727-4C1F-BDB1-E5FB3E0124E5,69C1F54F-384A-4D2D-A1B2-48FD67A79D01,780AE820-0885-43F8-97F0-4BB098ADA0A4,8164FE84-F63A-4AE4-BF9B-22A2C3D5B081,8B34BC74-EDD7-4404-899B-DF9B88440C7F,8CF93655-6040-4D6E-ABEC-875B6688786C,9325DF42-B099-432C-AF46-2AC00D7A85CD,975CC80F-368E-4A5C-86B8-FC169F435B12,9B7EBCEF-142B-40C1-9201-23210BCE1AF5,A1317ABE-555B-4E3A-80DC-A1B4D3E1B2F1,A19B49B8-3C13-40C9-817F-17FA26E9BC83,A2D20CAC-61E3-4D76-985A-E470EBC2F578,AB46789A-37A6-49EE-8277-417C18CCD503,ABAB80A3-9DC0-4A6D-8BF7-5EA2CD4973A6,B0887652-3305-46E0-B96B-49632FD9E884,BDD21345-6584-495C-9157-B44703F8ACA5,BEEB4EF0-3AC3-4D4F-B45E-8F1A3D1BEDB4,C23BDC16-F9D4-44DE-A6E3-545814095566,C4E53C81-B295-4270-9118-09C042CD745D,C584C160-83D1-4156-979F-18ABCC5E5CB2,D3AD5DAC-CACE-4FE3-9A4F-27FD1E1E0D85,D584784A-A088-4514-8D4E-55033999EA8A,D788D633-C46D-4CAB-8CA7-9D80FAA25F6E,D89630AB-C6FB-4E73-ADEC-86538A7FB05C,DB044D1E-2612-49DC-BB68-940C92F03DCA,E00B0F8A-0515-41D9-BAB7-CB80EDEB0967,E48DD354-5F3D-4E3E-A095-329F4FEAE49A,E7F576DE-F3E5-4CB8-9093-B0A9CC62F7E2,EFADE5A0-517D-4C7D-8AC6-4A9462D016A2,FD0DD5FA-1B03-4847-BCFA-E667613CD187,FF6591F6-5790-4C68-80BC-40EBE6406A9D

[Info] About to search for plist in base folder: /Users/fabian/Library/Developer/CoreSimulator/Devices/BE3E25FE-CFB7-4572-8D5C-B7EC0DC77AA3/data/Containers/Data/Application pathAfter: Library/Preferences/org.reactjs.native.example.test.plist in each of the apps: 05BB4537-3C35-4320-9648-42368F1C7ACA,1270E27A-0A82-4E7F-923B-D86CF2346024,1799674F-1EF1-4510-9F01-A18C00F0EB14,17F733D6-21C3-47F1-9B95-18C2C6E04F57,1B565069-D392-43AF-972E-C21763AA8F4F,1DD10550-CF1E-4328-9323-45B009180C7C,24978EBD-2CE0-4C03-B6E6-02469C710DC3,2743A147-0DF1-4910-81E3-9B5EF03FDFF5,2FB01430-D44F-4A04-A931-FAB1D3F022AC,36E37E0E-2F2D-4C1C-A600-F310637BAAC2,3C50EA36-B050-428E-8CD8-653608546C06,3FB00141-9243-4DCD-938E-09AE16514072,4316F007-17A2-4238-BD1D-2543B0E59E1F,44D8E181-5F3B-496F-BF98-D5AE7CFE6C88,46531F6D-6FD3-4EEC-8E12-C10836F107EC,4D9C3F82-12DC-448C-B8AE-DED3F2951326,4E7A051B-18AF-435E-B38B-9F2C984B577D,53B6D5CD-4907-4DCD-9EB6-482A77CB4537,5400E774-3B4B-488C-81D5-1A7C80244A8A,542B22EB-2612-410D-8A0A-F543D06FB9E2,54DB49A0-E051-4753-9A2B-137F7CB84AE0,645290CC-B727-4C1F-BDB1-E5FB3E0124E5,69C1F54F-384A-4D2D-A1B2-48FD67A79D01,780AE820-0885-43F8-97F0-4BB098ADA0A4,8164FE84-F63A-4AE4-BF9B-22A2C3D5B081,8B34BC74-EDD7-4404-899B-DF9B88440C7F,8CF93655-6040-4D6E-ABEC-875B6688786C,9325DF42-B099-432C-AF46-2AC00D7A85CD,975CC80F-368E-4A5C-86B8-FC169F435B12,9B7EBCEF-142B-40C1-9201-23210BCE1AF5,A1317ABE-555B-4E3A-80DC-A1B4D3E1B2F1,A19B49B8-3C13-40C9-817F-17FA26E9BC83,A2D20CAC-61E3-4D76-985A-E470EBC2F578,AB46789A-37A6-49EE-8277-417C18CCD503,ABAB80A3-9DC0-4A6D-8BF7-5EA2CD4973A6,B0887652-3305-46E0-B96B-49632FD9E884,BDD21345-6584-495C-9157-B44703F8ACA5,BEEB4EF0-3AC3-4D4F-B45E-8F1A3D1BEDB4,C23BDC16-F9D4-44DE-A6E3-545814095566,C4E53C81-B295-4270-9118-09C042CD745D,C584C160-83D1-4156-979F-18ABCC5E5CB2,D3AD5DAC-CACE-4FE3-9A4F-27FD1E1E0D85,D584784A-A088-4514-8D4E-55033999EA8A,D788D633-C46D-4CAB-8CA7-9D80FAA25F6E,D89630AB-C6FB-4E73-ADEC-86538A7FB05C,DB044D1E-2612-49DC-BB68-940C92F03DCA,E00B0F8A-0515-41D9-BAB7-CB80EDEB0967,E48DD354-5F3D-4E3E-A095-329F4FEAE49A,E7F576DE-F3E5-4CB8-9093-B0A9CC62F7E2,EFADE5A0-517D-4C7D-8AC6-4A9462D016A2,FD0DD5FA-1B03-4847-BCFA-E667613CD187,FF6591F6-5790-4C68-80BC-40EBE6406A9D

[Wed Dec 02 2020 13:38:59.660]  BUNDLE  ./index.js 

info Starting custom debugger by executing:, echo A debugger is not needed:  "/Users/fabian/Projects/jpmedia/test"
[Wed Dec 02 2020 13:38:59.181]  BUNDLE  ./index.js 

[Info] Packager is already running.

[Wed Dec 02 2020 13:39:11.227]  BUNDLE  ./index.js 

[Wed Dec 02 2020 13:39:11.286]  MAP  ./index.js 

[Wed Dec 02 2020 13:39:12.226]  LOG      JavaScript logs will appear in your environment console
warn Error: not opened
info Starting custom debugger by executing:, echo A debugger is not needed:  "/Users/fabian/Projects/jpmedia/test"
[Wed Dec 02 2020 13:39:32.180]  BUNDLE  ./index.js 



```
</details>

<details>
<summary>Developer Tools console</summary>

```text

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:304 [Extension Host] (node:19601) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:304
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1741   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
console.ts:137 [Extension Host] (node:19601) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
t.log @ console.ts:140
$logExtensionHostMessage @ mainThreadConsole.ts:29
_doInvokeHandler @ rpcProtocol.ts:365
_invokeHandler @ rpcProtocol.ts:365
_receiveRequest @ rpcProtocol.ts:306
_receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:584
fire @ ipc.net.ts:431
_receiveMessage @ ipc.net.ts:764
(anonymous) @ ipc.net.ts:624
fire @ event.ts:584
acceptChunk @ ipc.net.ts:174
(anonymous) @ ipc.net.ts:174
t @ ipc.net.ts:900
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
localProcessExtensionHost.ts:257 Extension Host
localProcessExtensionHost.ts:258 2020-12-02 13:38:42.257 xcodebuild[21222:218100]  DTDeviceKit: deviceType from df14881f78e963744243a4667c6536126886025a was NULL2020-12-02 13:38:42.314 xcodebuild[21222:218100]  DTDeviceKit: deviceType from df14881f78e963744243a4667c6536126886025a was NULL
localProcessExtensionHost.ts:257 Extension Host
localProcessExtensionHost.ts:258 2020-12-02 13:38:47.184 xcodebuild[21306:218877]  DTDeviceKit: deviceType from df14881f78e963744243a4667c6536126886025a was NULL2020-12-02 13:38:47.241 xcodebuild[21306:218888]  DTDeviceKit: deviceType from df14881f78e963744243a4667c6536126886025a was NULL
console.ts:137 [Extension Host] process [{…}]
log.ts:197   ERR loadedSources not supported: Error: loadedSources not supported
    at t.RawDebugSession.loadedSources (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3335:860)
    at N.getLoadedSources (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6206:316)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:180
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:240
    at Array.forEach (<anonymous>)
    at V.renderBody (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:131)
    at V.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1034:770)
    at V.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6941:800)
    at M.onDidAddViewDescriptors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6963:560)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6958:377
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at b.onDidChangeContext (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6354:152)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6347:480
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:94:782
    at t.PauseableEmitter.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at t.PauseableEmitter.resume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:628)
    at _.bufferChangeEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:431)
    at t.ViewModel.setFocus (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3341:724)
    at Y.focusStackFrame (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6231:980)
    at Y.launchOrAttachToSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6226:964)
    at async Y.doCreateSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6225:616)
    at async Y.startDebugging (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6222:924)
console.ts:137 [Extension Host] process [{…}]
log.ts:197   ERR loadedSources not supported: Error: loadedSources not supported
    at t.RawDebugSession.loadedSources (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3335:860)
    at N.getLoadedSources (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6206:316)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:180
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:240
    at Array.forEach (<anonymous>)
    at V.renderBody (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7166:131)
    at V.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1034:770)
    at V.render (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6941:800)
    at M.onDidAddViewDescriptors (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6963:560)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6958:377
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at b.onDidChangeContext (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6354:152)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6347:480
    at c.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:94:782
    at t.PauseableEmitter.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:67)
    at t.PauseableEmitter.resume (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:99:628)
    at _.bufferChangeEvents (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1931:431)
    at t.ViewModel.setFocus (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3341:724)
    at Y.focusStackFrame (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6231:980)
    at Y.launchOrAttachToSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6226:964)
    at async Y.doCreateSession (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6225:616)
    at async Y.startDebugging (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6222:924)



```
</details>

## Environment

Please tell us about your system and your project:

* `npx react-native doctor` or `npx expo doctor` if your project is using Expo:

```text

Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: 1.8.0_275
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0

Usage
 › Press f to try to fix issues.
 › Press e to try to fix errors.
 › Press w to try to fix warnings.
 › Press Enter to exit.
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✖ JDK
   - Version found: 1.8.0_275
   - Version supported: >= 8
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✖ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI

Errors:   2
Warnings: 0

```

* `envinfo`:

```text
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 708.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
    Gradle: 6.6 - /usr/local/bin/gradle
    Homebrew: 2.5.12 - /usr/local/bin/brew
    pip2: 20.2.4 - /usr/local/bin/pip2
    pip3: 20.1.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    CMake: 3.18.1 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1103.0.32.62 - /usr/bin/clang
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 19.03.12 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30
      Build Tools: 28.0.3, 29.0.0, 29.0.2, 30.0.1, 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.1 - /usr/bin/vim
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_275 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.5 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 83.0
    Safari: 14.0
```

* React Native Tools extension version: v1.1.1

**Comment by RookieZn** [comment]
Same issue for me with node v15.3.0, but it is ok with v14.5.1

**Comment by supagu** [comment]
I downgraded from node 15 to 14 (v14.15.1) and can confirm it is working properly for me with this version of node!

**Comment by SounD120** [comment]
Hi @supagu, @RookieZn . Could you please try to reproduce this on Node.js 15 and latest version of [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by RookieZn** [comment]
@SounD120  I can still reproduce on Node.js 15.3.0 and VS Code Insiders.
<img src="https://user-images.githubusercontent.com/17445652/101501257-7f6cea80-39aa-11eb-93d1-59081cccfd27.png" width="50%" />

**Comment by SounD120** [comment]
@supagu @RookieZn The reason of this bug has been found and fixed in upstream: https://github.com/microsoft/vscode-js-debug. This bug will be fixed when a new version of VS Code with the updated js-debug extension will be released.

**Comment by RookieZn** [comment]
This issue appears again with VS Code Version: 1.53.0-insider

**Comment by SounD120** [comment]
@RookieZn The extension cannot use the js-debug preview version that is used in VS Code Insiders, and the stable one is not yet released. Once 1.53 is released as stable the new version of stable js-debug with a fix should be contained in it.

**Comment by abegehr** [comment]
I'm having the issue on node 14 as well: `ERR loadedSources not supported: Error: loadedSources not supported`
I've tried setting the node version with an .nvmrc and setting the default alias on nvm directly to 14.15.1. No luck.
@RookieZn, @supagu, could you share more details on how you fixed the issue?

<img width="1552" alt="Screenshot 2021-01-23 at 00 35 59" src="https://user-images.githubusercontent.com/23075874/105560019-ff5cd300-5d12-11eb-8872-2d6f3a3c14e1.png">

**Comment by abegehr** [comment]
I'm having the issue on node 14 as well: ERR loadedSources not supported: Error: loadedSources not supported
I've tried setting the node version with an .nvmrc and setting the default alias on nvm directly to 14.15.1. No luck.
@RookieZn, @supagu, could you share more details on how you fixed the issue by setting the node version?
Screenshot of VSC: 
<img width="1552" alt="Screenshot 2021-01-23 at 00 38 49" src="https://user-images.githubusercontent.com/23075874/105560218-814cfc00-5d13-11eb-80f2-19eb3d3d8aa9.png">
The iPhone just shows a white screen at 100%, like in @RookieZn's comment: https://github.com/microsoft/vscode-react-native/issues/1465#issuecomment-740680706

**Comment by RedMickey** [comment]
Hi @abegehr, I tried to reproduce the issue on Node.js v14.15.1 the following way:

0. Created a plain React Native app
1. Set Node.js version using `nvm alias default 14.15.1` command
2. Started iOS debugging via `Debug iOS` scenario
3. I also got `ERR loadedSources not supported: Error: loadedSources not supported` error
4. But the application started successfully and the debugger could attach to it

Then I tested the app on Node.js v12.20.0 and got the same error, but I could debug the app without problems. I found out that this error message [is shown by VS Code](https://github.com/microsoft/vscode/blob/1.52.1/src/vs/workbench/contrib/debug/browser/rawDebugSession.ts#L445-L450) in case [`supportsLoadedSourcesRequest`](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_LoadedSources) parameter of the debug session isn't set to `true`. 
I added `supportsLoadedSourcesRequest` to the debug session configuration and then tried to debug the application using Node.js 15.6.0. In this case I didn't see the error in `Developer Tools console`, but as expected I couldn't attach to the app, since VS Code 1.52.1 hasn't had the fix for this issue yet. So I suppose `ERR loadedSources not supported: Error: loadedSources not supported` isn't the cause of the incorrect behavior.

Could you please add `"trace": "verbose"` parameter to you debug configuration, run it and send us outputs from `React Native Chrome Proxy` channel?

**Comment by RedMickey** [comment]
@abegehr Do you have a chance to look at this?

**Comment by RedMickey** [comment]
[VS Code version 1.53.0](https://code.visualstudio.com/updates/v1_53) and [js-debug extension v1.53.0](https://github.com/microsoft/vscode-js-debug/releases/tag/v1.53.0) with the fix have been released. We successfully tested debugging of an iOS React Native application using Node.js v15.6.0. It seems that the issue has been fixed, so I'm closing the issue.

**Comment by fnicastri** [comment]
Having still the same issue, or something very similar.
No luck event with node 16 nor 14.
Debugger is totally unusable right now

**Comment by RedMickey** [comment]
Hi @fnicastri and thanks for reaching us. I tried to debug a RN iOS app on Node.js v14.15.1 and v16.0.0 and couldn't reproduce this issue, debugging worked correctly. Could you please create a new issue for your specific case and describe your problem using our [issue template](https://github.com/microsoft/vscode-react-native/blob/master/.github/ISSUE_TEMPLATE/1-bug-report.md).
