### ISSUE TITLE
plugin does not work after last update of vscode

### ISSUE THREAD

**Issue by aferust** [Microsoft/vscode-react-native#276]
Plugin doesn't appear in Configurations/Select Environment section.
When I attempted to click on debug IOS or debug Android in existing project VSCode shows this error: Configured debug type 'reactnative' is not supported.

## Software versions
- React-Native VS Code extension version: 0.1.5
- VSCode version: 1.4.0
- OS platform and version: OSX El-Capitan 10.11.6
- React Native version: 0.27.2

**Comment by MSLaguana** [comment]
What do you mean by "Configurations/Select Environment" section?

If you go to the extensions section 
![image](https://cloud.githubusercontent.com/assets/14098340/17419945/b02b1190-5a54-11e6-8977-07b82ab5fa34.png) do you see the React Native Tools extension listed as installed?

**Comment by aferust** [comment]
about 20 minutes a go, vscode displayed a pop up for update. It happened after update. Yes, React Native Tools extension is listed there. I tried reinstalling both the extension and VSCode. When I click 'gear' icon now, react native option is not displayed for newly created projects. And I cannot start any debug session for existing react native projects receiving "Configured debug type 'reactnative' is not supported".

**Comment by MSLaguana** [comment]
I've just tried this out on an OSX 10.11.4 machine which I just updated to vscode 1.4.0, and it seems to be working correctly for me.

Can you please try deleting the `~/.vscode/extensions/vsmobile.vscode-react-native-0.1.5` folder and then re-install the extension and see if that helps? And failing that, could you check to see if your `~/.vscode/extensions/vsmobile.vscode-react-native-0.1.5/package.json` exists and contains something like 
```
"debuggers": [
{
"type": "reactnative",
```
which is what defines the React Native debugger.

**Comment by aferust** [comment]
deleting vsmobile.vscode-react-native-0.1.5 folder and reinstalling did not solve the problem. this is what I see in package.json now:
		"debuggers": [
			{
				"type": "reactnative",
				"label": "React Native",
				"program": "./out/debugger/nodeDebugWrapper.js",
				"runtime": "node",
				"enableBrekapointsFor": {
					"languageIds": [
						"javascript",
						"typescript",
						"javascriptreact",
						"typescriptreact"
					]
				},

**Comment by MSLaguana** [comment]
That's very odd, and as far as I can tell it should work. I'll bring this up with some of the vscode team and see if it's an issue on their end.

Thanks for letting us know about this.

**Comment by aferust** [comment]
I appreciate your efforts. Hope, it is solved soon.

**Comment by MSLaguana** [comment]
From the vscode issue, it seems that updating to a newer or older version of vscode solves the issue. If anyone else hits it, consider trying a beta version from https://code.visualstudio.com/insiders

**Comment by pietgk** [comment]
I had the same issue, installing the insiders solved the issue

**Comment by roura356a** [comment]
Installing the Insiders build has not fixed this issue for me. Any ideas?

**Comment by MSLaguana** [comment]
@roura356a and @levito could you please add details about the issue to https://github.com/Microsoft/vscode/issues/10148 if it is the same issue here (extension is installed, but no debugger seems to show up)

**Comment by weinand** [comment]
@MSLaguana there is a typo in the `enableBreakpointsFor` attribute of the package.json. It is incorrectly spelled `enableBrekapointsFor`. I do not yet know whether this is the culprit...

**Comment by tangkunyin** [comment]
@pietgk Trying to install 1.5.0-insider and install react native tool.It work for me

**Comment by pietgk** [comment]
i am already using it,
until now no occurring of the issue.

if it appears ill let you know immediatly

thx piet

**Comment by octref** [comment]
Hi all. The fix is verified in VSCode Insider 1.5.0. You can [download insider build](https://code.visualstudio.com/insiders) or wait for the next release.

**Comment by litingjun2015** [comment]
Hi, I have similar issue 'Configured debug type 'reactnative' is not supported.'

**Software versions**
VSCode version: 1.11.2
OS platform and version: OSX Sierra 10.12.3 
React Native version: 0.39.2

**Comment by ILI4S** [comment]
I have this issue on VSCode 1.23.0 on macOS High Sierra 10.13.4: 
```
Configured debug type 'reactnative' is not supported.
```

**Comment by navneetkarnani** [comment]
@ILI4S 
I Saw this on 1.23.0. Updated to 1.23.1 and the simulator launches.

**Comment by ruslan-bikkinin** [comment]
Hi @ILI4S 
Please try to follow suggestion from here: https://github.com/Microsoft/vscode-react-native/issues/276#issuecomment-388339960. If it doesn't help you, please submit new issue.
