### ISSUE TITLE
__debug__ is undefined since 3.0

### ISSUE THREAD

**Issue by mongris** [Microsoft/vscode-react-native#406]
I am fixing #363 and pulled request weeks ago(https://github.com/realm/realm-js/pull/855). But my fix is not working after VSCode and react-native extension updated.

I checked the commit history and found you exposed `__debug__.require` from 2.5, but ripped it off from 3.0 (migrated to node2 debug engine? )

Please help figure it out how to `require node package in app` in latest version.

Thank you!

**Comment by mongris** [comment]
I think it's a bug.
I can access `__debug__` when change 
https://github.com/Microsoft/vscode-react-native/blob/master/src/debugger/appWorker.ts#L45
to 

```javascript
global.__debug__ = {require: require};
```

**Comment by vladimir-kotikov** [comment]
@mongris, thanks for reporting. This is indeed a regression, caused by using module's scope instead of global's one for holding Node's `require` functionality available. This should be fixed once #401 is merged.

**Comment by mongris** [comment]
Thank you, I have changed locally and waiting form next release with #401.

**Comment by ajonno** [comment]
when will this fix be released ? i currently can't debug in VS Code am seeing this error: Unknown named module: './submit-analytics' when debugging with vs code

**Comment by mongris** [comment]
@ajonno `__debug__.require` has exported in vscode-react-native, and it's a issue owned by realm-js now.

realm-js should release the fix for `getContext` included in https://github.com/realm/realm-js/commit/f6347cf59fd71f90723f38f63152418ab642f348

**Comment by Arman92** [comment]
I still have this issue! 
Tried @mongris  solution (changed the lines of lib/index.js), did not work.

Anyone got a working fix?

**Comment by mongris** [comment]
@Arman92 what's version of your realm and vscode-react-native?
And you should replace the code `every time` when you upgrade npm packages.

I copied a `getContext` code in my project and replace manually after running any yarn or npm command. It's annoying but it should be working.
